spring.application.name=OrganizaDinheiro
# DATABASE
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# DRIVER
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# LOG SQL (debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CHAVE SECRETA JWT-SERVICE
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000